name: mini_data_platform
version: '1.0'
config-version: 2

profile: my_trino_project   # matches your profiles.yml

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  +materialized: table
